import urllib.parse
from datetime import datetime


def create_google_calendar_url(title, description, date_str):
    """生成 Google Calendar 添加链接"""
    # 默认设为当天全天事件，或者设为上午 9 点提醒
    try:
        dt = datetime.strptime(date_str, "%Y-%m-%d")
        # 格式: YYYYMMDDT090000Z
        start_time = dt.strftime("%Y%m%dT090000")
        end_time = dt.strftime("%Y%m%dT100000")
    except:
        return "#"

    base_url = "https://calendar.google.com/calendar/render"
    params = {
        "action": "TEMPLATE",
        "text": f"💳 Walle Reminder: {title}",
        "details": f"{description}\n\nGenerated by Walle AI.",
        "dates": f"{start_time}/{end_time}",
    }
    return f"{base_url}?{urllib.parse.urlencode(params)}"


def create_ics_file_content(title, description, date_str):
    """生成 .ics 文件内容 (适配 Apple / Outlook)"""
    try:
        dt = datetime.strptime(date_str, "%Y-%m-%d")
        dt_str = dt.strftime("%Y%m%d")
    except:
        dt_str = datetime.now().strftime("%Y%m%d")

    # ICS 标准格式
    ics_content = f"""BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Walle AI//Credit Card Agent//EN
BEGIN:VEVENT
SUMMARY:💳 Walle Reminder: {title}
DTSTART;VALUE=DATE:{dt_str}
DTEND;VALUE=DATE:{dt_str}
DESCRIPTION:{description}
STATUS:CONFIRMED
SEQUENCE:0
BEGIN:VALARM
TRIGGER:-PT9H
DESCRIPTION:Reminder
ACTION:DISPLAY
END:VALARM
END:VEVENT
END:VCALENDAR"""
    return ics_content
