import urllib.parse
from datetime import datetime

import streamlit as st

# src/utils.py (追加在文件末尾或合适位置)
from google import genai

# src/utils.py


@st.cache_resource
def get_available_models(api_key):
    """
    检查可用模型并根据性能分类。
    优先使用 Gemini 3 系列 (根据你的 check_models 结果定制)
    """
    # 默认兜底
    default_models = {
        "🚀 Fast (Gemini 1.5 Flash)": "gemini-1.5-flash",
        "⚖️ Balanced (Gemini 1.5 Pro)": "gemini-1.5-pro",
    }

    try:
        client = genai.Client(api_key=api_key)
        all_models = list(client.models.list())
        # 提取纯净的模型名 (去掉 models/ 前缀)
        model_names = [m.name.replace("models/", "") for m in all_models]

        found_models = {}

        # --- 1. 🚀 Fast: 追求速度与性价比 ---
        # 优先用 Gemini 3 Flash Preview (兼顾速度与智商)
        if "gemini-3-flash-preview" in model_names:
            found_models["🚀 Fast (Gemini 3 Flash)"] = "gemini-3-flash-preview"
        elif "gemini-2.0-flash" in model_names:
            found_models["🚀 Fast (Gemini 2.0 Flash)"] = "gemini-2.0-flash"
        elif "gemini-1.5-flash" in model_names:
            found_models["🚀 Fast (Gemini 1.5 Flash)"] = "gemini-1.5-flash"

        # --- 2. 🧠 Smart: 追求最强推理 (处理 5/24 或复杂分析) ---
        # 优先用 Gemini 3 Pro Preview
        if "gemini-3-pro-preview" in model_names:
            found_models["🧠 Smart (Gemini 3 Pro)"] = "gemini-3-pro-preview"
        elif "gemini-2.0-pro-exp" in model_names:  # 假如未来有
            found_models["🧠 Smart (Gemini 2.0 Pro)"] = "gemini-2.0-pro-exp"
        elif "gemini-1.5-pro" in model_names:
            found_models["🧠 Smart (Gemini 1.5 Pro)"] = "gemini-1.5-pro"

        # --- 3. ⚡️ Experimental: 尝鲜 Google 最新黑科技 ---
        # 比如 2.0 Flash Exp 或 Thinking 模式
        if "gemini-2.0-flash-thinking-exp" in model_names:
            found_models["⚡️ Thinking (Gemini 2.0 Exp)"] = (
                "gemini-2.0-flash-thinking-exp"
            )
        elif "gemini-2.0-flash-exp" in model_names:
            found_models["⚡️ Experimental (Gemini 2.0 Flash)"] = "gemini-2.0-flash-exp"

        if not found_models:
            return default_models

        # 排序：Fast -> Smart -> Experimental
        # 使用自定义顺序，而不是字母顺序
        order = ["🚀", "🧠", "⚡️", "⚖️"]
        sorted_keys = sorted(
            found_models.keys(),
            key=lambda x: next((i for i, k in enumerate(order) if k in x), 99),
        )

        return {k: found_models[k] for k in sorted_keys}

    except Exception as e:
        print(f"Model check failed: {e}")
        return default_models


def create_google_calendar_url(title, description, date_str):
    """生成 Google Calendar 添加链接"""
    # 默认设为当天全天事件，或者设为上午 9 点提醒
    try:
        dt = datetime.strptime(date_str, "%Y-%m-%d")
        # 格式: YYYYMMDDT090000Z
        start_time = dt.strftime("%Y%m%dT090000")
        end_time = dt.strftime("%Y%m%dT100000")
    except:
        return "#"

    base_url = "https://calendar.google.com/calendar/render"
    params = {
        "action": "TEMPLATE",
        "text": f"{title}",
        "details": f"{description}\n\nGenerated by Walle AI.",
        "dates": f"{start_time}/{end_time}",
    }
    return f"{base_url}?{urllib.parse.urlencode(params)}"


def create_ics_file_content(title, description, date_str):
    """生成 .ics 文件内容 (适配 Apple / Outlook)"""
    try:
        dt = datetime.strptime(date_str, "%Y-%m-%d")
        dt_str = dt.strftime("%Y%m%d")
    except:
        dt_str = datetime.now().strftime("%Y%m%d")

    # ICS 标准格式
    ics_content = f"""BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Walle AI//Credit Card Agent//EN
BEGIN:VEVENT
SUMMARY:{title}
DTSTART;VALUE=DATE:{dt_str}
DTEND;VALUE=DATE:{dt_str}
DESCRIPTION:{description}
STATUS:CONFIRMED
SEQUENCE:0
BEGIN:VALARM
TRIGGER:-PT9H
DESCRIPTION:Reminder
ACTION:DISPLAY
END:VALARM
END:VEVENT
END:VCALENDAR"""
    return ics_content
